import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Navbar from "@/components/Navbar";
import GoogleAd from "@/components/GoogleAd";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vasudhev | हिन्दी न्यूज, Breaking News, Latest News, Top Headlines",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
            <div className="container w-full">
              <div className="wrapper px-4 lg:px-20 m-auto lg:max-w-[1256px] max-w-full">
                <Topbar />
                <Navbar />
                <GoogleAd />
                {children}
                <Footer />
              </div>
            </div>
      </body>
    </html>
  );
}
